### ISSUE TITLE
How do you evaluate the pika/Runway

### ISSUE THREAD

**Issue by FanqingM** [Hritikbansal/videophy#2]
How do you evaluate the pika/Runway? It seems that do not have apis. Could you share the code to evaluate this?
Thank you !

**Comment by Hritikbansal** [comment]
Hi @FanqingM,

Thanks for your interest. Yes, pika/runway don't have an API. We bought the subscription for large-scale generations and wrote some scripts to get the videos. @Rafa-zy can you help with the scripts here or over email?
